{% set version = "0.5.1" %}

package:
  name: oceans
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/o/oceans/oceans-{{ version }}.tar.gz
  sha256: 0419833e6634f13f0716133b4eb4e5ecdd218c07c5d5c5c025e8e57549f4b181

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - scipy
    - matplotlib
    - pandas
    - gsw
    - seawater
    - shapely
    - netcdf4
    - ctd

test:
  imports:
    - oceans

about:
  home: https://github.com/pyoceans/python-oceans
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Misc functions for oceanographic data analysis.'

extra:
  recipe-maintainers:
    - ocefpaf
