{% set version = "0.4.0" %}

package:
  name: oceans
  version: {{ version }}

source:
  fn: oceans-{{ version }}.tar.gz
  url: https://github.com/pyoceans/python-oceans/archive/v{{ version }}.tar.gz
  sha256: ba085af687170f793ab142fc1920d26389c8c1ae515ffbba11e3d34bb0a0a47b

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - pandas
    - gsw
    - seawater
    - shapely
    - netcdf4
    - ctd

test:
  imports:
    - oceans

about:
  home: https://github.com/pyoceans/python-oceans
  license: BSD 3-Clause
  summary: 'Misc functions for oceanographic data analysis.'

extra:
  recipe-maintainers:
    - ocefpaf
