{% set version = "0.8.1" %}

package:
  name: oceans
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/o/oceans/oceans-{{ version }}.tar.gz
  sha256: 235954b7c1b2cc9f63d1bade94741fe0fc58efb512c66e613a716f82d6a39d06

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - scipy
    - matplotlib-base
    - pandas
    - gsw
    - seawater
    - shapely
    - netcdf4
    - ctd

test:
  imports:
    - oceans

about:
  home: https://github.com/pyoceans/python-oceans
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Misc functions for oceanographic data analysis'

extra:
  recipe-maintainers:
    - ocefpaf
