{% set version = "0.7.0" %}

package:
  name: oceans
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/o/oceans/oceans-{{ version }}.tar.gz
  sha256: cc071c8b0bf5e6ce3f875b93d62c658926c2d710bece5fead1253bc9cb68e8b0

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - scipy
    - matplotlib
    - pandas
    - gsw
    - seawater
    - shapely
    - netcdf4
    - ctd

test:
  imports:
    - oceans

about:
  home: https://github.com/pyoceans/python-oceans
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Misc functions for oceanographic data analysis'

extra:
  recipe-maintainers:
    - ocefpaf
