{% set version = "0.3.0" %}

package:
    name: oceans
    version: {{ version }}

source:
    fn: oceans-{{ version }}.tar.gz
    url: https://github.com/pyoceans/python-oceans/archive/v{{ version }}.tar.gz
    sha256: 163370ae480bfc112c61848dc4b667caa347d92e16d0ff6ef296b62c40f62c3a

build:
    number: 0
    script: python setup.py install --single-version-externally-managed  --record record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - numpy
        - scipy
        - matplotlib
        - pandas
        - gsw
        - seawater
        - shapely
        - netcdf4
        - ctd

test:
    imports:
        - oceans

about:
    home: http://pypi.python.org/pypi/oceans/
    license: MIT
    summary: 'Misc functions for oceanographic data analysis.'

extra:
    recipe-maintainers:
        - ocefpaf
