{% set name = "oceans" %}
{% set version = "1.1.4" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/oceans-{{ version }}.tar.gz
  sha256: c578e6c6bce5f31cbd16d6bfa4b6f74c31dc13f0c5cb57cf5ef179557daa4d79

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - setuptools-scm >=3.4
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - cmcrameri
    - contourpy
    - gsw
    - matplotlib-base >=3.6.0
    - numpy >=1.20
    - pandas >=1.0.1
    - seawater
    # optional
    - scipy
    - shapely
    - netcdf4
    - ctd

test:
  imports:
    - oceans
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pyoceans/python-oceans
  summary: Misc functions for oceanographic data analysis
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ocefpaf
