{% set version = "0.8.0" %}

package:
  name: oceans
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/o/oceans/oceans-{{ version }}.tar.gz
  sha256: de37f4227943ed69220a823f0d6e3ddadbee84385ac5c570efe58b4e88b7c1cf

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - scipy
    - matplotlib
    - pandas
    - gsw
    - seawater
    - shapely
    - netcdf4
    - ctd

test:
  imports:
    - oceans

about:
  home: https://github.com/pyoceans/python-oceans
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Misc functions for oceanographic data analysis'

extra:
  recipe-maintainers:
    - ocefpaf
