travis:
  secure:
    BINSTAR_TOKEN: o5ptcuKr8FtOyk1u66Hb+yh8xbvTJHo1SIqKeBlA9lucyttxMquxZhTElkZw+ovKfbMa+4spYobGbkxDRdS5ONi5hX8i5OxQtwIQb3zYxlEOviw9sPsc6nCFXIcMCqX6G5usFMTNsvdlB9KwdxrLc6N5dFRP21bqb682nC8VcnEG2NEBygyXRH4+N5MK7g5DOTrivbEpsOIkWRJ7qcEbAe+hzenz+HFTWkO6rc5n3tJ7MeB6nU5lyU/yTmQOKGjT+pvj/N5nrsynx8Dj9wksvBF5fPd52m4pswkBzRbq0FxkotjN0DTVUdkL6P7YR1Rp1f3utyu/w5evTxiMjem/4lrPI9Ku5ReKtkXXaruExDNm2ijTEZSax/mIBOorY42o6QP2lVFSTQ05CcYg6p3MHfAoC+fhM0oSJWeOORQ7yEa9IHJXj+GfLFdRgFtQNo335Q7DRJpR5pIsuwH5SgnHC+UUltJNPzNhmW9KZu4NQGxpyJi/DpTsCEW2JLAsdU9O3SHN3B+RQOvCTwEq3YRguJvw5migyn2HJO2kSmUwzBxW8qD9H/SxlhikGY7XXUzjTOIQJmTO64YE87hlUWG1Xxnpte7zSdwA754kcYj7kuWA/Oy4C3vNKlEKCn7tIZkUiHxsi59TliMyu4nlFVTRkCu0lxpc0R22m24FNolNKG4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
