travis:
  secure:
    BINSTAR_TOKEN: NCzl/mJYYE5Xh96z7tyELJ5+00P14uOFJoQLRZ1UFhcGI/9sklaor0P+x7R8EYycUvJj2s6OgmMIkBHFOh3Cq3MueZzdPqKMzj/+3IWjZ772yz+tAVbqiX29pqVSh38T5B4ZcneeseXW7fEWIRm3tsfNJAAeqX86vqvt2I+YMP1Y/NOHq0ZzoMlGtJALjl6kIvPzE5efiqYNQGUY9S6yUD36+NZkcXOfHmDCan7Ge1W+a4tkASgIbQXLLsqrmPfM/6vKOKubZ1e+Iqu+RrzA5mnK1Mloh9g5MBvCCiUY+Na/bZc+dqC+Pp4gVf5kzt/QwSNW5JoF6GUCA3tkkVqbs/PF+6LzRzz7jHNuRJd+h9ThYCLferBn2okKjdoCNEdidfMoPIBLO9c4sYeE6fmaYrAjCu+9b+OXOFykHSHXxurg8kfpmzVxWggCw9dYm6F1T86GOssOZDzxL6EKmklJNlpCLfqxrhC9XQrk4wiIX+O+Y2+P2sw8ZXkHqtMrfKSAi2YysuzsfDcyNC/gu83YO3xzvfbxvVceI7hD4gwePTpyrWTLstEtfKcFwkC2kLxrhAch7S4SjLBW/3qmIP7F8iysJUWYyG+34etnCzhFNl6Zn7hnjLeCAO9VX1HyzjmKQ67HExanhxtKdeLP+K0vfRh8p1VY8cEB5a5rbqvS6Cs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
